version: "3.8"
services:
  jobmanager:
    build: .
    ports:
      - "8081:8081"
    # if you have only one job, you can use this command
    command: standalone-job --hostname host.docker.internal --port 9999
    # otherwise, you need to specify the job class name
    # command: standalone-job --job-classname org.apache.flink.streaming.examples.socket.SocketWindowWordCount --hostname host.docker.internal --port 9999
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 1
    networks:
      - flink-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  taskmanager:
    build: .
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
    networks:
      - flink-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  flink-network:
    driver: bridge
    external: true